const subCategoriesValues = (userId: number) =>
`(1,${userId},"Food & Beverage"),
(1,${userId},"Transportation"),
(1,${userId},"Rentals"),
(1,${userId},"Water Bill"),
(1,${userId},"Phone Bill"),
(1,${userId},"Electricity Bill"),
(1,${userId},"Gas Bill"),
(1,${userId},"Television Bill"),
(1,${userId},"Internet Bill"),
(1,${userId},"Other Utility Bills"),
(2,${userId},"Home Maintenance"),
(2,${userId},"Vehicle Maintenance"),
(2,${userId},"Medical Check Up"),
(2,${userId},"Insurances"),
(2,${userId},"Education"),
(2,${userId},"Houseware"),
(2,${userId},"Personal Items"),
(2,${userId},"Pets"),
(2,${userId},"Home Services"),
(3,${userId},"Fitness"),
(3,${userId},"Makeup"),
(2,${userId},"Other Expense"),
(3,${userId},"Gifts & Donations"),
(3,${userId},"Streaming Service"),
(3,${userId},"Fun Money"),
(4,${userId},"Investment"),
(4,${userId},"Loan"),
(4,${userId},"Repayment"),
(4,${userId},"Pay Interest"),
(7,${userId},"Outgoing Transfer"),
(5,${userId},"Debt Collection"),
(5,${userId},"Debt"),
(5,${userId},"Collect Interest"),
(6,${userId},"Other Income"),
(6,${userId},"Salary"),
(8,${userId},"Incoming Transfer");`;

export default subCategoriesValues;